services:
  fp-studio-rocm:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ipc: host
    shm_size: 8G
    image: blastbeng/fp-studio-rocm:latest
    runtime: "amd"
    container_name: fp-studio-rocm
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HIP_PLATFORM=amd
      - PYTORCH_HIP_FALLBACK=1
      - PYTORCH_HIP_ALLOC_CONF=expandable_segments:True,max_split_size_mb:512
      - HSA_ENABLE_SDMA=1
      - HSA_ENABLE_PEER_SDMA=1
    #  - LD_PRELOAD=/usr/local/lib/libforcegttalloc.so
    devices:
      - /dev/dxg
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - /usr/lib/wsl/lib/libdxcore.so:/usr/lib/libdxcore.so
      - /opt/rocm/lib/libhsa-runtime64.so.1:/opt/rocm/lib/libhsa-runtime64.so.1
      - "./loras:/app/loras"
      - "/mnt/d/generated:/app/outputs"
      - "./.framepack:/app/.framepack"
      - "./modules/toolbox/model_esrgan:/app/modules/toolbox/model_esrgan"
      - "./modules/toolbox/model_rife:/app/modules/toolbox/model_rife"
      - "$HOME/.cache/huggingface:/app/hf_download"
